"""Initial Migration

Revision ID: 0d186a3e99aa
Revises: 
Create Date: 2020-03-11 01:48:46.635189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d186a3e99aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='client_pkey'),
                    sa.UniqueConstraint('name', name='client_name_key')
                    )
    op.create_table('artist',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('portfolio_link', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='artist_pkey'),
                    sa.UniqueConstraint('name', name='artist_name_key')
                    )
    op.create_table('project',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('client_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('is_open', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['client_id'], ['client.id'], name='project_client_id_fkey'),
                    sa.PrimaryKeyConstraint(
                        'id', 'client_id', name='project_pkey'),
                    sa.UniqueConstraint('name', name='project_name_key')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('artist')
    op.drop_table('client')
    # ### end Alembic commands ###
